#!/usr/bin/env bash
# prompts the user to choose whether to update the package list before installing a new package

# Prompt theuser for choice
read -p "Do you want to update package lists? (y/n): " choice

# Check the users choice
if [ "$choice" == "y" ] || [ "$choice" == "Y" ]; then
     sudo apt-get update
     if [ $? -ne 0 ]; then
        echo " Update interrupted. Exiting."
        exit 1
    fi
fi

# Prompt the user for the package name
read -p "Enter the package name you want to install: " package_name

#install the package
sudo apt-get install "$package_name"